main/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    # ===================== Tasks ====================================
    url(r'^$', 'theory.views.show_theory', {'theory_id': 0}, name='show_theory'),
    url(r'^tasks/(?P<task_id>\d+)$', 'tasks.views.solve_task', name='solve_task'),
    # Urls for debugging
    url(r'^show_all_hints$', 'tasks.views.show_all_hints', name='debug_show_all_hints'),
    url(r'^show_filtered_hints$', 'tasks.views.show_filtered_hints', name='show_filtered_hints'),
    url(r'^show_all_solutions$', 'tasks.views.show_all_solutions', name='debug_show_all_solutions'),
    url(r'^show_filtered_solutions$', 'tasks.views.show_filtered_solutions', name='show_filtered_solutions'),
    url(r'^show_all_complaints$', 'tasks.views.show_all_complaints', name='show_all_complaints'),

    # ===================== Tasks - Solving ====================================
    url(r'^get_grade$', 'tasks.views.get_grade', name='get_grade'),
    url(r'^get_milestone_id$', 'tasks.views.get_milestone_id', name='get_milestone_id'),
    url(r'^get_filtered_hint$', 'tasks.views.get_filtered_hint', name='get_filtered_hint'),
    url(r'^get_plan_hint$', 'tasks.views.get_plan_hint', name='get_plan_hint'),
    url(r'^send_step$', 'tasks.views.check_step', name='send_step'),
    url(r'^save_step_easy_interface$', 'tasks.views.save_step_easy_interface', name='save_step_easy_interface'),
    url(r'^remove_step/(?P<step_id>\d+)$', 'tasks.views.remove_step', name='remove_step'),
    url(r'^update_solution/(?P<step_id>\d+)$', 'tasks.views.update_solution', name='update_solution'),
    url(r'^modify_step/(?P<step_id>\d+)$', 'tasks.views.modify_step', name='modify_step'),
    url(r'^get_easy_template/(?P<milestone_id>\d+)$', 'tasks.views.get_easy_template', name='get_easy_template'),
    url(r'^get_easy_data_check_data/(?P<milestone_id>\d+)$', 'tasks.views.get_easy_data_check_data', name='get_easy_data_check_data'),
    url(r'^get_easy_data_depend_on/(?P<milestone_id>\d+)$', 'tasks.views.get_easy_data_depend_on', name='get_easy_data_depend_on'),
    url(r'^complain$', 'tasks.views.complain', name='complain'),
    
    # ======================Logs========================================================================================================== 
    url(r'^write_log$', 'tasks.views.write_log', name='write_log'),
    url(r'^remove_logs$', 'students.views.remove_logs', name='remove_logs'),
    url(r'^logs$', 'students.views.all_logs', name='all_logs'),
    url(r'^show_logs/(?P<session_id>\d+)$', 'students.views.show_logs', name='show_logs'),

    # ===================== Students =====================================================================================================
    url(r'^attempts$', 'students.views.all_attempts', name='all_attempts'),
    url(r'^session_attempts/(?P<session_id>\d+)$', 'students.views.session_attempts', name='session_attempts'),
    url(r'^student/(?P<student_id>\d+)$', 'students.views.student_attempts', name='student_attempts'),
    url(r'^session/(?P<session_id>\d+)$', 'students.views.session_attempts', name='session_attempts'),

    # ===================== Students - Attempts ====================================
    url(r'^attempt/(?P<attempt_id>\d+)$', 'students.views.show_attempt', name='show_attempt'),
    url(r'^remove_attempts$', 'students.views.remove_attempt', name='remove_attempts'),
    url(r'^save$', 'students.views.save_attempt', name='save_attempt'),
    url(r'^load/(?P<saving_id>\d+)$', 'tasks.views.load_saving', name='load_attempt'),
    url(r'^hint_attempt/(?P<attempt_id>\d+)', 'students.views.hint_attempt', name='hint_attempt'),
    url(r'^close_attempt/(?P<grade>\d+)$', 'students.views.close_attempt', name='close_attempt'),
    url(r'^revive_attempt/(?P<attempt_id>\d+)$', 'students.views.revive_attempt', name='revive_attempt'),
    url(r'^set_active_attempt/(?P<attempt_id>\d+)$', 'tasks.views.set_active_attempt', name='set_active_attempt'),

    # ===================== Students - Authentication ====================================
    url(r'students/login/$', 'django.contrib.auth.views.login',
                             {'template_name': 'login.html'}, name='login'),
    url(r'students/logout/$', 'django.contrib.auth.views.logout_then_login',
                              {'login_url': '/students/login/'}, name='logout'),

    # ===================== Theory ====================================
    url(r'^theory/(?P<theory_id>\d+)$', 'theory.views.show_theory', name='show_theory'),
    url(r'^theory/$', 'theory.views.show_theory', {'theory_id': 0}, name='show_theory'),

    # ===================== Admin ====================================
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    #=======================Tutoring flow Control ====================
    url(r'^suggest_help$', 'tasks.tutoring_flow_control.suggest_help', name='suggest_help'),
    url(r'^get_filtered_hint$', 'tasks.views.get_filtered_hint', name='get_filtered_hint'),

    url(r'^admin_tools/', include('admin_tools.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor.urls')),
)

students/models.py
# coding: utf-8

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

from tasks.models import Task, Hint, Milestone, Expression


# Now this is default Profile class
class Student(models.Model):
    user = models.OneToOneField(User, unique=True)

    def __unicode__(self):
        return str(self.user.username)


def create_user_profile(sender, instance, created, **kwargs):
    """ This code is also for replacement default auth.User to students.Student """
    if created:
        Student.objects.create(user=instance)

post_save.connect(create_user_profile, sender=User)


class Session(models.Model):
    
    identificator = models.CharField(max_length=255, verbose_name='Идентификатор сессии')
    date = models.DateField(auto_now_add=True)
    student = models.ForeignKey(Student, related_name='sessions', verbose_name='Студент')
    
    def add_to_log(self, data, time, log_type=''):
        self.save()
        log = Log(log_data=data, log_time=time, log_type=log_type, session=self)
        log.save()

class Attempt(models.Model):
    STATUS_CHOICES = [
        (-1, 'fail'),
        (1, 'success'),
        (0, 'in_progress'),
    ]

    status = models.IntegerField(choices=STATUS_CHOICES, default=0, verbose_name='Статус')
    session = models.ForeignKey(Session, verbose_name='Сессия')
    task = models.ForeignKey(Task, related_name='attempts', verbose_name='Задача')
    task_parameters = models.TextField(blank=True, null=True, verbose_name='Параметры')
    hints = models.ManyToManyField(Hint, blank=True, verbose_name='Взятые подсказки')
    help_enabled = models.BooleanField(default=False)
    time_start = models.DateTimeField(auto_now_add=True)
    time_end = models.DateTimeField(auto_now=True)
    grade = models.FloatField(blank=True, null=True, default=0)

class Log(models.Model):
    log_type = models.CharField(max_length=255, blank=True, null=True)
    log_time = models.DateTimeField()
    log_data = models.CharField(max_length=512)
    session = models.ForeignKey(Session, related_name='logs')

class Step(models.Model): 
    STATUS_CHOICES = [
        (-1, 'fail'),
        (1, 'success'),
        (0, 'in_progress'),
    ]

    INTERFACE_CHOICES = [
        (1, 'hard'),
        (0, 'easy'),
    ]

    time = models.DateTimeField(auto_now=True)
    number = models.IntegerField(default=0)
    status = models.IntegerField(choices=STATUS_CHOICES, default=0, verbose_name='Статус')
    milestone = models.ForeignKey(Milestone, blank=True, null=True, verbose_name='Этап')
    attempt = models.ForeignKey(Attempt)
    interface = models.IntegerField(choices=INTERFACE_CHOICES, default=0, verbose_name='Интерфейс')
    data_hard = models.TextField(blank=True, null=True)
    data_easy = models.TextField(blank=True, null=True)
    required_expression = models.ForeignKey(Expression, blank=True, null=True)

    def __unicode__(self):
        return u'Шаг ' + str(self.id)

class Saving(models.Model):
    attempt = models.ForeignKey(Attempt)
    date = models.DateTimeField(auto_now_add=True)

tasks/models.py
# -*- coding: utf-8 -*-

from django.db import models
from support.models import Theory
# Create your models here.



class Notation(models.Model):    
    name = models.CharField(max_length=255, verbose_name='Название')
    notation = models.CharField(max_length=255, verbose_name='Значение')    

    def __unicode__(self):
        return u'%s <=> %s' % (self.name, self.notation)

class Task(models.Model):
    name = models.CharField(blank=True, null=True, max_length=255, verbose_name='Название')
    description = models.TextField(blank=True, null=True, verbose_name='Условие')

    def __unicode__(self):
        return u'Задача "%s"' % self.name
    
    class Meta:
        ordering = ['name']

class TaskNotation(models.Model):
    task = models.ForeignKey(Task, verbose_name='Задача', related_name='task_notations')
    notation = models.ForeignKey(Notation, verbose_name='Обозначение')
    priority = models.IntegerField(default=0)

    class Meta:
        ordering = ['priority']

class Milestone_type(models.Model):
    name = models.CharField(blank=True, null=True, max_length=255, verbose_name='Название')

    def __unicode__(self):
        return self.name
    
class Easy_interface_setting(models.Model):
    name = models.CharField(blank=True, max_length=255, verbose_name='Название')
    view = models.TextField(blank=True, verbose_name='Визуальное представление легкого интерфейса' )
    variables = models.TextField(blank=True, verbose_name='Переменные легкого интерфейса' ) 
    check_data = models.TextField(blank=True, verbose_name='Значения/формула/скрипт для проверки легкого интерфейса' )
    CHECK_TYPE = [
        (1, 'Формула'),
        (2, 'Конкретные значения'),
        (3, 'Скрипт'),
    ]
    check_type = models.IntegerField(choices=CHECK_TYPE, default=1, verbose_name='Тип проверки легкого интерфейса')
    formula_view = models.TextField(blank=True, verbose_name='Формула для компактного отображения введенного шага' )

    def __unicode__(self):
        return u'Этап "%s"' % self.name
       
class Milestone(models.Model):
    name = models.CharField(blank=True, null=True, max_length=255, verbose_name='Название')
    type = models.ForeignKey(Milestone_type, blank=True, null=True, verbose_name='Тип')
    is_multiple = models.BooleanField(blank=True, default=False, verbose_name='Комбинаторный этап')
    hard_data = models.TextField(blank=True, null=True, verbose_name='Данные для трудного интерфейса')
    easy_interface_setting = models.ForeignKey(Easy_interface_setting, blank=True, null=True, verbose_name='Настройка легкого интерфейса')
    plan_hint = models.TextField(blank=True, null=True, verbose_name='Подсказка по ходу решения задачи')
    depends_on = models.ManyToManyField("self", blank=True, null=True, verbose_name='От каких этапов зависит проверка')

    def __unicode__(self):
        return u'Этап "%s"' % self.name
    
class EquivRel(models.Model):
    name = models.CharField(blank=True, null=True, max_length=255, verbose_name="Название")
    task = models.ForeignKey(Task, verbose_name='Задача')
    equivalent_milestones = models.ManyToManyField(Milestone, blank=True, null=True)
    
    def __unicode__(self):
        return u'Эквивалентность "%s"' % self.name
    
class Expression(models.Model):
    text = models.TextField(verbose_name='Текст выражения')
    milestone = models.ForeignKey(Milestone, verbose_name='Этап')
    easy_interface_setting = models.ForeignKey(Easy_interface_setting, blank=True, null=True, verbose_name='Настройка легкого интерфейса')

    def __unicode__(self):
        return u'Выражение "%s"' % self.text


class Hint(models.Model):
    TYPE_CHOICES = [
        (1, 'Теоретическая'),
        (2, 'Схематическая'),
        (3, 'Конкретная'),
    ]
    KIND_CHOICES = [
        (1, 'короткая подсказка'),
        (2, 'ссылка на теоретический материал'),
        (3, 'ссылка на задачу для переключения'),
    ]
    hint_type = models.IntegerField(choices=TYPE_CHOICES, verbose_name=u'Тип подсказки')
    hint_kind = models.IntegerField(choices=KIND_CHOICES, verbose_name=u'Вид подсказки', default=1)
    milestone = models.ForeignKey(Milestone, blank=True, null=True, verbose_name='Этап')
    idx = models.IntegerField(blank=True, null=True, verbose_name='Очередность')
    text = models.TextField(blank=True, null=True, verbose_name='Текст подсказки')
    for_easy = models.BooleanField(default=True, verbose_name='Актуальна при легком интерфейсе')

    def get_hint_save(self, student):
        #attempts = Attempt.objects.filter(student=student, task=self.hint_task)
        sessions = [ s for s in student.sessions.all() ]
        attempts = [attempt for attempt in self.hint_task.attempts.filter(session__in=sessions)]

        if attempts.count() > 0:
            return attempts[attempts.count()-1]
        else:
            return None

    class Meta:
        ordering = ['hint_type','idx']

class Solution(models.Model):
    milestones = models.ManyToManyField(Milestone, blank=True, null=True)
    name = models.CharField(blank=True, null=True, max_length=255, verbose_name="Название")
    task = models.ForeignKey(Task, verbose_name='Задача')
    for_hints = models.BooleanField(verbose_name='Использовать решения для подсказок', default=False)
    not_necessary = models.BooleanField(verbose_name='Решение с необязательными этапами', default=False)

    def __unicode__(self):
        return u'Решение "%s"' % self.name
    
class SolutionMilestone(models.Model):
    solution = models.ForeignKey(Solution, verbose_name='Решение', related_name='solution_milestones')
    milestone = models.ForeignKey(Milestone, verbose_name='Этап')
    priority = models.IntegerField(default=0)

    class Meta:
        ordering = ['priority']

tasks/templates/complaints_list.html
{% block content %}

<ul>
{% for student in students %}
	<li>
		<p>Студент: {{student.user.username}}</p>
		{% for session in student.sessions.all %}
			{% for attempt in session.attempt_set.all %}
			  {% for step in attempt.step_set.all %}
			  	{% ifequal step.status 0 %}		  	
			  	  <p><b>Задача: {{attempt.task.name}}</b></p>
			  	  <p>
			  	    {{step.time|time:"H:i" }} <b>Шаг </b>{{step.number}}, тип: {{step.milestone.type}}, интерфейс: 
	                {% ifequal step.interface 1 %} трудный, {% else %} легкий, {% endifequal %}
	                <br/><br/>
	                {% if step.interface %}{{ step.data_hard }}{% else %}\({{ step.data_easy }}\){% endif %}<br /><br/>
	 			  </p>	
			    {% endifequal %}
			  {% endfor %}
			{% endfor %}
		{% endfor %}
	</li>
{% endfor %}
</ul>

{% endblock content %}

tasks/templates/debug_hints_list.html
{% block content %}

{% if hint_type == 4 %}
<h1>All hints </h1>
{% for m in milestones %}
	<hr>
<p><b>Milestone: {{ m.name }}, {{ m.hard_data }}</b></p>
	Hints:
<ul>
	{% for hint in m.hint_set.all %}
	<li><b>{% if hint.hint_type == 1 %} Теоретическая {% elif hint.hint_type == 2 %}
	Схематическая {% elif hint.hint_type == 3 %} Конкретная {% else %} {% endif %} {{hint.idx}} </b><br>  
			{% if hint.hint_kind == 3 %} Переключитесь на более простую <a
			href="#">задачу </a>%} 
			{%elif hint.hint_kind == 2 %} 
			Посмотрите теоретический <a href="#">материал </a>
			{%else %}
			{% endif %} 
			 {{hint.text}} 
	</li>{% endfor %}
</ul>
<hr>

{% endfor %}
{% endif %}

{% if hint_type == 1 %}
<h1>Theoretic hints </h1>
{% for m in milestones %}
	<hr>
<p><b>Milestone: {{ m.name }}, {{ m.hard_data }}</b></p>
	Hints:
<ul>
	{% for hint in m.hint_set.all %} {% if hint.hint_type == 1 %}
	<li>Type: {{hint.hint_type}} <br> 
		Text: 
			{% if hint.hint_kind == 3 %} Переключитесь на более простую <a
			href="#">задачу </a>%} 
			{%elif hint.hint_kind == 2 %} 
			Посмотрите теоретический <a href="#">материал </a>
			{%else %}
			{% endif %} 
			 {{hint.text}} 
		{% endif %}	
	</li>{% endfor %}
</ul>
<hr>

{% endfor %}
{% endif %}

{% if hint_type == 2 %}
<h1>Schematic hints </h1>
{% for m in milestones %}
	<hr>
<p><b>Milestone: {{ m.name }}, {{ m.hard_data }}</b></p>
	Hints:
	<ul>
	{% for hint in m.hint_set.all %} {% if hint.hint_type == 2 %}
	<li>Type: {{hint.hint_type}} <br> 
		Text: 
			{% if hint.hint_kind == 3 %} Переключитесь на более простую <a
			href="#">задачу </a>%} 
			{%elif hint.hint_kind == 2 %} 
			Посмотрите теоретический <a href="#">материал </a>
			{%else %}
			{% endif %} 
			 {{hint.text}} 
		{% endif %}	
	</li>{% endfor %}
	</ul>
	<hr>

{% endfor %}
{% endif %}

{% if hint_type == 3 %}
<h1>Concrete hints </h1>
{% for m in milestones %}
	<hr>
	<p><b>Milestone: {{ m.name }}, {{ m.hard_data }}</b></p>
	Hints:
	<ul>
	{% for hint in m.hint_set.all %} {% if hint.hint_type == 3 %}
	<li>Type: {{hint.hint_type}} <br> 
		Text: 
			{% if hint.hint_kind == 3 %} Переключитесь на более простую <a
			href="#">задачу </a>%} 
			{%elif hint.hint_kind == 2 %} 
			Посмотрите теоретический <a href="#">материал </a>
			{%else %}
			{% endif %} 
			 {{hint.text}} 
		{% endif %}	
	</li>{% endfor %}
	</ul>
	<hr>

{% endfor %}
{% endif %}
{% endblock content %}

tasks/templates/debug_solutions_list.html
{% block content %}

{% for s in solution_milestones %}
	<hr>
<p><b>Solution: {{ s.solution.name }}, Milestone: {{ s.milestone.name }}</b></p><br/>
 		{{s.milestone.hard_data}}
<br/>
{{s.milestone.plan_hint}}
<br/>
<hr>
{% endfor %}
{% endblock content %}

tasks/templates/select_hints.html
{% extends "base.html" %} {% block head %}
<script type="text/javascript">
$(function() {
    	MathJax.Hub.Config({
    	    tex2jax: {
    	        inlineMath: [['$','$'], ['\\(','\\)']],
    	        displayMath: [ ['$$','$$'], ["\\[","\\]"] ],
    	        processEscapes: true
    	    },
    	     jax: ["input/TeX", "output/HTML-CSS"],
    	     "HTML-CSS": {
    	     availableFonts: ["TeX"],
    	     preferredFont: "TeX",
    	     webFont: "TeX",
    	     imageFont: null }
  		});
	$('#main-container').on('click', '.get_hint', function(){    
    $('#main-container').find('.hint-type').html($(this).attr('data-hint'));
    $('#main-container').find('.dropdown-toggle-hint').html($(this).html());
	});
	$('#main-container').on('click', '.get_task', function(){    
    $('#main-container').find('.task-id').html($(this).attr('data-task'));
    $('#main-container').find('.dropdown-toggle-task').html($(this).html());
	});
	$('#main-container').on('click', '#form', function(){ 
		task_id = $('#main-container').find('.task-id').html();
		hint_type = $('#main-container').find('.hint-type').html();
		$.get('/show_filtered_hints',
				{'task_id': task_id, 'hint_type': hint_type}, function(data){
					$('#report').html(data);
					MathJax.Hub.Queue(["Typeset", MathJax.Hub, 'report']);
		});
	});
});
</script>
<br/><br/>
<h1><center>Отчет по подсказкам</center></h1>
{% endblock %} {% block content %}
<div id="main-container">
	Выбрать тип подсказки: &nbsp; <span class="dropdown step-hint" href="#">
		<a href="#" class="dropdown-toggle-hint" data-toggle="dropdown">................</a>
		<ul class="dropdown-menu" style="margin-top: 10px;">
			<li><a href="#" class="get_hint" data-hint="1">Теоретическая</a></li>
			<li><a href="#" class="get_hint" data-hint="2">Схематическая</a></li>
			<li><a href="#" class="get_hint" data-hint="3">Конкретная</a></li>
			<li><a href="#" class="get_hint" data-hint="4">Все</a></li>
		</ul>
	</span> &nbsp; Выбрать задачу: <span class="dropdown step-hint" href="#">
		<a href="#" class="dropdown-toggle-task" data-toggle="dropdown">................</a>
		<ul class="dropdown-menu" style="margin-top: 10px;">
			{% for task in tasks %}
			<li><a href="#" class="get_task" data-task={{task.id}}>{{task.name}}</a>
			</li> {% endfor %}
		</ul>
	</span>
	&nbsp;
	<a href="#" class="btn btn-primary" id="form" >  
		Сформировать отчет
	</a>
	<div class="hint-type hide">0</div>
	<div class="task-id hide">0</div>
</div>
<div id="report"></div>
{% endblock content %}

tasks/templates/select_solutions.html
{% extends "base.html" %} {% block head %}
<script type="text/javascript">
$(function() {
    	MathJax.Hub.Config({
    	    tex2jax: {
    	        inlineMath: [['$','$'], ['\\(','\\)']],
    	        displayMath: [ ['$$','$$'], ["\\[","\\]"] ],
    	        processEscapes: true
    	    },
    	     jax: ["input/TeX", "output/HTML-CSS"],
    	     "HTML-CSS": {
    	     availableFonts: ["TeX"],
    	     preferredFont: "TeX",
    	     webFont: "TeX",
    	     imageFont: null }
  		});
	$('#main-container').on('click', '.get_task', function(){    
    $('#main-container').find('.task-id').html($(this).attr('data-task'));
    $('#main-container').find('.dropdown-toggle-task').html($(this).html());
	});
	$('#main-container').on('click', '#form', function(){ 
		task_id = $('#main-container').find('.task-id').html();
		$.get('/show_filtered_solutions',
				{'task_id': task_id}, function(data){
					$('#report').html(data);
					MathJax.Hub.Queue(["Typeset", MathJax.Hub, 'report']);
		});
	});
});
</script>
<br/><br/>
<h1><center>Отчет по решениям</center></h1>
{% endblock %} {% block content %}
<div id="main-container">
	Выбрать задачу: <span class="dropdown step-hint" href="#">
		<a href="#" class="dropdown-toggle-task" data-toggle="dropdown">................</a>
		<ul class="dropdown-menu" style="margin-top: 10px;">
			{% for task in tasks %}
			<li><a href="#" class="get_task" data-task={{task.id}}>{{task.name}}</a>
			</li> {% endfor %}
		</ul>
	</span>
	&nbsp;
	<a href="#" class="btn btn-primary" id="form" >  
		Сформировать отчет
	</a>
	<div class="task-id hide">0</div>
</div>
<div id="report"></div>
{% endblock content %}