main/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    # ===================== Tasks ====================================
    url(r'^$', 'theory.views.show_theory', {'theory_id': 0}, name='show_theory'),
    url(r'^tasks/(?P<task_id>\d+)$', 'tasks.views.solve_task', name='solve_task'),
    # Urls for debugging
    url(r'^show_all_hints$', 'tasks.views.show_all_hints', name='debug_show_all_hints'),
    url(r'^show_filtered_hints$', 'tasks.views.show_filtered_hints', name='show_filtered_hints'),
    url(r'^show_all_solutions$', 'tasks.views.show_all_solutions', name='debug_show_all_solutions'),
    url(r'^show_filtered_solutions$', 'tasks.views.show_filtered_solutions', name='show_filtered_solutions'),
    url(r'^show_all_complaints$', 'tasks.views.show_all_complaints', name='show_all_complaints'),

    # ===================== Tasks - Solving ====================================
    url(r'^get_grade$', 'tasks.views.get_grade', name='get_grade'),
    url(r'^get_milestone_id$', 'tasks.views.get_milestone_id', name='get_milestone_id'),
    url(r'^get_filtered_hint$', 'tasks.views.get_filtered_hint', name='get_filtered_hint'),
    url(r'^get_plan_hint$', 'tasks.views.get_plan_hint', name='get_plan_hint'),
    url(r'^send_step$', 'tasks.views.check_step', name='send_step'),
    url(r'^save_step_easy_interface$', 'tasks.views.save_step_easy_interface', name='save_step_easy_interface'),
    url(r'^remove_step/(?P<step_id>\d+)$', 'tasks.views.remove_step', name='remove_step'),
    url(r'^update_solution/(?P<step_id>\d+)$', 'tasks.views.update_solution', name='update_solution'),
    url(r'^modify_step/(?P<step_id>\d+)$', 'tasks.views.modify_step', name='modify_step'),
    url(r'^get_easy_template/(?P<milestone_id>\d+)$', 'tasks.views.get_easy_template', name='get_easy_template'),
    url(r'^get_easy_data_check_data/(?P<milestone_id>\d+)$', 'tasks.views.get_easy_data_check_data', name='get_easy_data_check_data'),
    url(r'^get_easy_data_depend_on/(?P<milestone_id>\d+)$', 'tasks.views.get_easy_data_depend_on', name='get_easy_data_depend_on'),
    url(r'^complain$', 'tasks.views.complain', name='complain'),
    
    # ======================Logs========================================================================================================== 
    url(r'^write_log$', 'tasks.views.write_log', name='write_log'),
    url(r'^remove_logs$', 'students.views.remove_logs', name='remove_logs'),
    url(r'^logs$', 'students.views.all_logs', name='all_logs'),
    url(r'^show_logs/(?P<session_id>\d+)$', 'students.views.show_logs', name='show_logs'),

    # ===================== Students =====================================================================================================
    url(r'^attempts$', 'students.views.all_attempts', name='all_attempts'),
    url(r'^session_attempts/(?P<session_id>\d+)$', 'students.views.session_attempts', name='session_attempts'),
    url(r'^student/(?P<student_id>\d+)$', 'students.views.student_attempts', name='student_attempts'),
    url(r'^session/(?P<session_id>\d+)$', 'students.views.session_attempts', name='session_attempts'),

    # ===================== Students - Attempts ====================================
    url(r'^attempt/(?P<attempt_id>\d+)$', 'students.views.show_attempt', name='show_attempt'),
    url(r'^remove_attempts$', 'students.views.remove_attempt', name='remove_attempts'),
    url(r'^save$', 'students.views.save_attempt', name='save_attempt'),
    url(r'^load/(?P<saving_id>\d+)$', 'tasks.views.load_saving', name='load_attempt'),
    url(r'^hint_attempt/(?P<attempt_id>\d+)', 'students.views.hint_attempt', name='hint_attempt'),
    url(r'^close_attempt/(?P<grade>\d+)$', 'students.views.close_attempt', name='close_attempt'),
    url(r'^revive_attempt/(?P<attempt_id>\d+)$', 'students.views.revive_attempt', name='revive_attempt'),
    url(r'^set_active_attempt/(?P<attempt_id>\d+)$', 'tasks.views.set_active_attempt', name='set_active_attempt'),

    # ===================== Students - Authentication ====================================
    url(r'students/login/$', 'django.contrib.auth.views.login',
                             {'template_name': 'login.html'}, name='login'),
    url(r'students/logout/$', 'django.contrib.auth.views.logout_then_login',
                              {'login_url': '/students/login/'}, name='logout'),

    # ===================== Theory ====================================
    url(r'^theory/(?P<theory_id>\d+)$', 'theory.views.show_theory', name='show_theory'),
    url(r'^theory/$', 'theory.views.show_theory', {'theory_id': 0}, name='show_theory'),

    # ===================== Admin ====================================
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    #=======================Tutoring flow Control ====================
    url(r'^suggest_help$', 'tasks.tutoring_flow_control.suggest_help', name='suggest_help'),
    url(r'^get_filtered_hint$', 'tasks.views.get_filtered_hint', name='get_filtered_hint'),

    url(r'^admin_tools/', include('admin_tools.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor.urls')),
)

theory/models.py
# coding: utf-8
from django.db import models
from tasks.models import Task

# Create your models here.
class Theory_section(models.Model):
    name = models.CharField(blank=True, max_length=300, verbose_name='Раздел теории')
    
    def __unicode__(self):
        return self.name
    
    class Meta:
        ordering = ['name']

class Theory(models.Model):
    section = models.ForeignKey(Theory_section, blank=True, null=True, verbose_name='Раздел теории')
    tasks = models.ManyToManyField(Task, blank=True, null=True, verbose_name='Список задач')
    title = models.CharField(max_length=300, verbose_name='Название')
    text = models.TextField(verbose_name='Содержание')

    def __unicode__(self):
        return self.title
    
    class Meta:
        ordering = ['title']

theory/views.py
from django.shortcuts import render_to_response
from django.http import Http404
from theory.models import Theory, Theory_section
from django.contrib.auth.decorators import login_required
from django.template import RequestContext
from students.models import Student, Session, Attempt, Step, Log, Saving
from datetime import datetime

@login_required
def show_theory(request, theory_id):
    
    student = Student.objects.get(user=request.user)
    
    if not 'student_session_id' in request.session:
        session = Session(identificator=str(datetime.now()) + ' ' + str(student.id), student=student)
        session.save()
        request.session['student_session_id'] = session.id
        
    else:
        try:
            session = Session.objects.get(id=int(request.session['student_session_id']))
        except Session.DoesNotExist:
            session = None
    
    request.session.set_expiry(8640)
    
    try:
        if theory_id != 0:
            text = Theory.objects.get(id=theory_id)
        else:
            text = ''
        contents = Theory_section.objects.select_related().all()
    except Theory.DoesNotExist:
        return Http404

    return render_to_response("theory.html", \
    				{'text': text, 'contents': contents}, \
    				context_instance=RequestContext(request))

theory/templates/theory.html
	{% extends "base.html" %}


{% block page_title %} Теория: {{ text.title }}{% endblock %}

{% block head %}
<link href="/static/lib/jquery.treeview/jquery.treeview.css" rel="stylesheet">
<script src="/static/lib/jquery/jquery.cookie.min.js" type="text/javascript"></script>
<script src="/static/lib/jquery.treeview/jquery.treeview.min.js" type="text/javascript"></script>
<script src="/static/front/logging.js" type="text/javascript"></script>
<script type="text/javascript">
	$(function() {
		// ================ Configuration =================
		$("#tree").treeview({
			control: "#treecontrol",
			persist: "cookie",
			cookieId: "treeview",
			persist: "location"
		});
		// ================ END Configuration =============


		var logger = new Logger();

		// current_theory_id = 0, когда открыта просто главная страница теории
		var current_theory_id = {% if text.id %}{{text.id}}{% else %}0{% endif %};	
		
		//введена потому что дублируются события window on focus
		var window_focus = false;

		// ============== Логирование различных событий ==========
		// 1. Открытие теории
		
		logger.add_to_log("STUDENT OPEN THEORY " + current_theory_id);
		
		// 2. Закрытие вкладки (окна) с теорией
		$(window).bind('beforeunload', function(){
			logger.add_to_log("STUDENT CLOSE THEORY " + current_theory_id);
		    // Отправим оставшиеся логи
		    logger.send_log();
		});

		// 3. Смена вкладки, т.е. потеря фокуса на окно (вкладку) с теорией
		 $(window).blur(function() {
			if(window_focus) {
			  	window_focus = false;
			  	logger.add_to_log('STUDENT LOST_FOCUS THEORY ' + current_theory_id);  
			}
		 });

		// 4. Возврат к уже открытой вкладке с теорией
		 $(window).focus(function() {
			 if(!window_focus) {
				 logger.add_to_log('STUDENT FOCUS THEORY ' + current_theory_id);
			  	 window_focus = true;
			 }	 
		 });
		
		$('.itask-container').on('click', '#tree', function(){
			logger.add_to_log('STUDENT CLICK THEORY_CONTENTS ');
		});

		// 5. Сколько по времени двигался курсор мышки без остановки
		// @INFO: запись "(function(){" используется для того, чтобы все
		// переменные внутри не могли быть перезаписаны вовне, т.е. они видны только внутри функции
		(function(){
			var timer = null;
			var isMouseMoving = false;
			var secondsMoving = 0;

			function mouseStop() { 
				isMouseMoving = false
				secondsMoving = ((new Date).getTime() - secondsMoving)/1000
				logger.add_to_log('STUDENT MOVE_MOUSE THEORY ' + secondsMoving);
			}

			$('body').mousemove(function(){
				clearTimeout(timer)
				// Считаем, что мышка остановила непрерывное движение,
				// если она не двигалась дольше 1с
				timer = setTimeout(mouseStop, 1000)
				if (!isMouseMoving) {
					// Начало движения
					isMouseMoving = true
					secondsMoving = (new Date).getTime()
				}
			});
		})();
		

		// 6. Сколько по времени студент скроллил страницу
		(function(){
			var timer = null;
			var isScrolling = false;
			var secondsScrolling = 0;

			function mouseStop() { 
				isScrolling = false
				secondsScrolling = ((new Date).getTime() - secondsScrolling)/1000
				logger.add_to_log('STUDENT SCROLL THEORY ' + secondsScrolling);
			}

			$(window).scroll(function(){
				clearTimeout(timer)
				// Считаем, что скроллили, если между скроллами
				// прошло не больше  1с
				timer = setTimeout(mouseStop, 1000)
				if (!isScrolling) {
					// Начало движения
					isScrolling = true
					secondsScrolling = (new Date).getTime()
				}
			});
		})();
		// ============== END Логирование различных событий ==========
		 
	});
</script>
{% endblock %}

{% block content%}
	<div class="row-fluid" style="margin-top: 15px">
		<div class="span5 well">
			{# Список глав #}
			<ul class="treeview" id="tree">
				{% for title in contents %}
				<li>
					<span>{{title.name}}</span>
					<ul style="display:none;">
					{# Список параграфов и задачи в рамках главы #}
					{% for paragraph in title.theory_set.all %}
						<li>
							<a href="/theory/{{paragraph.id}}">{{paragraph.title}}</a>
							{% if paragraph.tasks.all %}
								<ul style="display:none;">
								{% for task in paragraph.tasks.all %}
									<li class="task-link"><a href="/tasks/{{task.id}}">{{task.name}}</a></li>
								{% endfor %}
								</ul>
							{% endif %}
						</li>
					{% endfor %}
					</ul>
				</li>
				{% endfor %}
			</ul>
		</div>
		{# Содержимое теории #}
		<div class="span7">
			<h3>{{ text.title }}</h3>
			{{text.text|safe}}
		</div>
	</div>
{% endblock %}